In [1]:
import pandas as pd
# First load the dataset into pandas dataframe
dataset = pd.read_csv('training-set.csv',delimiter=',')

In [2]:
dataset.head()

Tick#  offsetTime  IMU_ATTI(0):numSats  IMU_ATTI(0):barometer:Raw  \
0  339062105       0.000                   14                  1188.3093   
1  339314363       0.066                   14                  1188.1595   
2  339465911       0.105                   14                  1188.1595   
3  339648466       0.152                   14                  1188.2122   
4  339821470       0.197                   14                  1188.2122   

   IMU_ATTI(0):barometer:Smooth  IMU_ATTI(0):accel:X  IMU_ATTI(0):accel:Y  \
0                     1188.0585            -0.007624            -0.162505   
1                     1188.0468            -0.007572            -0.161164   
2                     1188.0468            -0.007572            -0.161164   
3                     1188.0359            -0.008646            -0.153160   
4                     1188.0359            -0.008646            -0.153160   

   IMU_ATTI(0):accel:Z  IMU_ATTI(0):accel:Composite  IMU_ATTI(0):gyro:X  ...  \
0            -0.980750                     0.994151           -0.013848  ...   
1            -0.981163                     0.994339            0.049079  ...   
2            -0.981163                     0.994339            0.049079  ...   
3            -0.982913                     0.994812            0.535372  ...   
4            -0.982913                     0.994812            0.535372  ...   

   MotorCtrl:PWM:RFront  MotorCtrl:PWM:LFront  MotorCtrl:PWM:LBack  \
0                   NaN                   NaN                  NaN   
1                   NaN                   NaN                  NaN   
2                   NaN                   NaN                  NaN   
3                   NaN                   NaN                  NaN   
4                   NaN                   NaN                  NaN   

   MotorCtrl:PWM:RBack  AirCraftCondition:fsmState  \
0                  NaN                           0   
1                  NaN                           0   
2                  NaN                           0   
3                  NaN                           1   
4                  NaN                           1   

   AirCraftCondition:nearGround  AirCraftCondition:landState  \
0                          True                            1   
1                          True                            1   
2                          True                            1   
3                          True                            1   
4                          True                            1   

   AirCraftCondition:UP_acc_t  AirCraftCondition:UP_TF_t  Operating_Phase  
0                         0.0                          0          Resting  
1                         0.0                          0          Resting  
2                         0.0                          0          Resting  
3                         0.0                          0          Resting  
4                         0.0                          0          Resting  

[5 rows x 142 columns]

In [3]:
#For calculating total no of rows
rows = dataset.count()[0]
print("total number of rows =", rows)
#For calculating total no of cols
cols = len(dataset.columns)
print("total number of columns =",cols)
# For calculating Number of columns having non-numeric values
non_numeric_columns = dataset.select_dtypes(exclude=['number'])
num = len(non_numeric_columns.columns)
print(f"Number of columns having non-numeric values= {num}")
# For calculating Number of missing values
missing_values = dataset.isnull().sum()
missing_values = missing_values.sort_values(ascending=False)
print("Number of missing values in each column:")
missing_columns = [(column, missing_number) for column, missing_number in missing_values.items() if missing_number>0]
missing_columns.sort(key=lambda x: x[1], reverse=True)
summary =   f"total number of rows = {rows}\n"\
                f"total number of columns = {cols}\n"\
                f"number of columns having non-numeric values = {non_numeric_columns}\n"\
                f"columns with missing values = {missing_columns}\n"
print(summary)

total number of rows = 5085
total number of columns = 142
Number of columns having non-numeric values= 5
Number of missing values in each column:
total number of rows = 5085
total number of columns = 142
number of columns having non-numeric values =          GPS:dateTimeStamp IMUEX(0):err IMUEX(1):err  \
0     2019-07-07T20:11:12Z         NONE         NONE   
1     2019-07-07T20:11:12Z         NONE         NONE   
2     2019-07-07T20:11:12Z         NONE         NONE   
3     2019-07-07T20:11:12Z         NONE         NONE   
4     2019-07-07T20:11:12Z         NONE         NONE   
...                    ...          ...          ...   
5080  2019-07-07T20:15:22Z         NONE         NONE   
5081  2019-07-07T20:15:22Z         NONE         NONE   
5082  2019-07-07T20:15:22Z         NONE         NONE   
5083  2019-07-07T20:15:22Z         NONE         NONE   
5084  2019-07-07T20:15:22Z         NONE         NONE   

      AirCraftCondition:nearGround Operating_Phase  
0                       

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27532\72791066.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  rows = dataset.count()[0]


In [4]:
target_column = 'Operating_Phase'
x = dataset.drop(columns=[target_column])  # X contains all columns except the target column
y = dataset[target_column]
print(x)

           Tick#  offsetTime  IMU_ATTI(0):numSats  IMU_ATTI(0):barometer:Raw  \
0      339062105       0.000                   14                  1188.3093   
1      339314363       0.066                   14                  1188.1595   
2      339465911       0.105                   14                  1188.1595   
3      339648466       0.152                   14                  1188.2122   
4      339821470       0.197                   14                  1188.2122   
...          ...         ...                  ...                        ...   
5080  1298285682     249.149                   16                  1187.0396   
5081  1298419437     249.184                   16                  1187.2435   
5082  1298717112     249.261                   16                  1187.2435   
5083  1298930277     249.316                   16                  1187.1661   
5084  1299063252     249.351                   16                  1187.1661   

      IMU_ATTI(0):barometer:Smooth  IMU

In [5]:
from sklearn.model_selection import train_test_split
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y,train_size=0.75, test_size=0.25, random_state=12346)

columns_to_drop = ['GPS:dateTimeStamp']

X_train = X_train.drop(columns=columns_to_drop)
X_test = X_test.drop(columns=columns_to_drop)

print("X Train Data")
print(X_train)
print("X Test Data")
print(X_test)

ModuleNotFoundError: No module named 'sklearn'

In [21]:
# from sklearn.preprocessing import LabelEncoder

# y_train_ohe = pd.get_dummies(y_train)
# correlation_matrix = X_train.corrwith(y_train_ohe, axis=0)
# #print(correlation_matrix)
# correlation_matrix = abs(correlation_matrix)

# # Initialize a LabelEncoder
# label_encoder = LabelEncoder()

# # Encode the categorical labels in y_train
# y_train_encoded = label_encoder.fit_transform(y_train)
# y_test_encoded = label_encoder.fit_transform(y_test)
# # Compute the correlation matrix
# correlation_matrix = y_train_ohe.corrwith(pd.Series(y_train_encoded))

# # Drop rows with NaN correlation scores
# correlation_matrix.dropna(inplace=True)

# top75_corr = correlation_matrix.abs()#.nlargest(100)
# top75_df = pd.DataFrame({'variable': top75_corr.index, 'corr_score': top75_corr.values})
# print(top75_df)

     variable  corr_score
0    Climbing    0.017392
1    Hovering    0.013627
2     Resting    0.009482
3  Taking-Off    0.004685


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_21372\399023340.py:4: FutureWarning: The default value of numeric_only in DataFrame.corrwith is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = X_train.corrwith(y_train_ohe, axis=0)


In [31]:
categorical_columns = X_train.select_dtypes(exclude=['number']).columns
X_train_ohe = pd.get_dummies(X_train,  columns=categorical_columns, dtype=int)
X_test_ohe = pd.get_dummies(X_test,  columns=categorical_columns, dtype=int)
print(categorical_columns)

Index(['IMUEX(0):err', 'IMUEX(1):err', 'AirCraftCondition:nearGround'], dtype='object')


In [33]:
from sklearn.preprocessing import MinMaxScaler
#X_scaled = (X - X.min()) / (X.max() - X.min())
# Create an instance of MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled_mm = scaler.fit_transform(X_train_ohe)
X_test_scaled_mm = scaler.transform(X_test_ohe)
print(X_test_scaled_mm)

[[0.49759063 0.49759175 0.75       ... 0.         1.         0.        ]
 [0.98626143 0.98626033 0.5        ... 0.         0.         1.        ]
 [0.4654619  0.46546034 0.75       ... 0.         1.         0.        ]
 ...
 [0.94396971 0.94397055 0.75       ... 0.         1.         0.        ]
 [0.57866206 0.57866221 0.75       ... 0.         1.         0.        ]
 [0.17440098 0.17440074 0.75       ... 0.         1.         0.        ]]


C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\preprocessing\_data.py:473: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\sklearn\preprocessing\_data.py:474: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)


In [34]:
missing_values = X_train_ohe.isnull().sum()
missing_counts = pd.DataFrame({'variable_name': missing_values.index, 'num_of_missing_values': missing_values.values})
X_train_ohe_imputed = X_train_ohe.fillna(X_train_ohe.mean())
X_test_ohe_imputed = X_test_ohe.fillna(X_test_ohe.mean())

In [49]:
from sklearn.impute import SimpleImputer

# Create an imputer instance
imputer = SimpleImputer(strategy='median')  # You can choose a different strategy like 'median' or 'most_frequent'

# Fit and transform the imputer on your feature matrix
X_train_imputed = imputer.fit_transform(X_train_ohe_imputed)
X_test_imputed = imputer.transform(X_test_ohe_imputed)


In [60]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

y_train_encoded = label_encoder.fit_transform(y_train)
y_test_encoded = label_encoder.fit_transform(y_test)

# # Drop rows with missing values (NaN)
# X_train = X_train.dropna()
# y_train_encoded = y_train[X_train.index]  # Adjust the target variable accordingly

# # Similarly, drop rows with missing values in the test data
# X_test = X_test.dropna()
# y_test_encoded = y_test[X_test.index]  # Adjust the target variable accordingly

correlation_matrix = X_train_ohe_imputed.corrwith(pd.Series(y_train_encoded))
print(y_train_encoded)

correlation_matrix.dropna(inplace=True)
top75_corr = correlation_matrix.abs()#.nlargest(70)
top75_df = pd.DataFrame({'variable': top75_corr.index, 'corr_score': top75_corr.values})
print(top75_df)

[0 0 0 ... 1 0 0]
                               variable  corr_score
0                                 Tick#    0.004182
1                            offsetTime    0.004182
2                   IMU_ATTI(0):numSats    0.015660
3             IMU_ATTI(0):barometer:Raw    0.022762
4          IMU_ATTI(0):barometer:Smooth    0.020224
..                                  ...         ...
118          AirCraftCondition:fsmState    0.009518
119         AirCraftCondition:landState    0.000189
120          AirCraftCondition:UP_acc_t    0.008056
121  AirCraftCondition:nearGround_False    0.017976
122   AirCraftCondition:nearGround_True    0.017976

[123 rows x 2 columns]


In [81]:
top75_variables = top75_df['variable'].tolist()

X_train_t75 = X_train_ohe_imputed[top75_variables]
X_test_t75 = X_test_ohe_imputed[top75_variables]
print(len(top75_variables))

123


In [52]:
from sklearn.ensemble import RandomForestClassifier

# Create a Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Fit the model to the training data
rf_classifier.fit(X_train_imputed, y_train_encoded)

y_pred = rf_classifier.predict(X_test_imputed)

In [54]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Evaluate the model
accuracy = accuracy_score(y_test_encoded, y_pred)
report = classification_report(y_test_encoded, y_pred)
conf_matrix = confusion_matrix(y_test_encoded, y_pred)

print(f"Accuracy: {accuracy}")
print(report)
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 0.9984276729559748
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       694
           1       1.00      1.00      1.00       492
           2       1.00      1.00      1.00        32
           3       1.00      1.00      1.00         5
           4       1.00      1.00      1.00        49

    accuracy                           1.00      1272
   macro avg       1.00      1.00      1.00      1272
weighted avg       1.00      1.00      1.00      1272

Confusion Matrix:
[[693   1   0   0   0]
 [  1 491   0   0   0]
 [  0   0  32   0   0]
 [  0   0   0   5   0]
 [  0   0   0   0  49]]


In [72]:
from sklearn.preprocessing import StandardScaler

judge_df = pd.read_csv('judge-set.csv',delimiter=',')

judge_df.drop(columns=['GPS:dateTimeStamp'], inplace=True)

# # Perform one-hot encoding on the judge dataset
#judge_ohe = pd.get_dummies(judge_df)
judge_ohe = pd.get_dummies(judge_df,  columns=categorical_columns, dtype=int)
print(judge_ohe.columns)

judge_ohe.head()

Index(['Tick#', 'offsetTime', 'IMU_ATTI(0):numSats',
       'IMU_ATTI(0):barometer:Raw', 'IMU_ATTI(0):barometer:Smooth',
       'IMU_ATTI(0):accel:X', 'IMU_ATTI(0):accel:Y', 'IMU_ATTI(0):accel:Z',
       'IMU_ATTI(0):accel:Composite', 'IMU_ATTI(0):gyro:X',
       ...
       'MotorCtrl:PWM:LBack', 'MotorCtrl:PWM:RBack',
       'AirCraftCondition:fsmState', 'AirCraftCondition:landState',
       'AirCraftCondition:UP_acc_t', 'AirCraftCondition:UP_TF_t',
       'IMUEX(0):err_GPS_CONSIST_ERROR', 'IMUEX(0):err_NONE',
       'IMUEX(1):err_NONE', 'AirCraftCondition:nearGround_True'],
      dtype='object', length=141)


Tick#  offsetTime  IMU_ATTI(0):numSats  IMU_ATTI(0):barometer:Raw  \
0  143222258       0.000                   11                   1230.502   
1  143393138       0.044                   11                   1230.502   
2  143566452       0.089                   11                   1230.404   
3  143758752       0.139                   11                   1230.404   
4  143892690       0.174                   11                   1230.404   

   IMU_ATTI(0):barometer:Smooth  IMU_ATTI(0):accel:X  IMU_ATTI(0):accel:Y  \
0                     1229.9978             0.066096             0.108688   
1                     1229.9978             0.066096             0.108688   
2                     1229.9976             0.070309             0.122074   
3                     1229.9976             0.070309             0.122074   
4                     1229.9994             0.063894             0.110587   

   IMU_ATTI(0):accel:Z  IMU_ATTI(0):accel:Composite  IMU_ATTI(0):gyro:X  ...  \
0            -0.990579                     0.998714            0.081449  ...   
1            -0.990579                     0.998714            0.081449  ...   
2            -0.989888                     0.999861           -0.701116  ...   
3            -0.989888                     0.999861           -0.701116  ...   
4            -0.990387                     0.998588           -0.357004  ...   

   MotorCtrl:PWM:LBack  MotorCtrl:PWM:RBack  AirCraftCondition:fsmState  \
0                  NaN                  NaN                           0   
1                  NaN                  NaN                           0   
2                  NaN                  NaN                           1   
3                  NaN                  NaN                           1   
4                  NaN                  NaN                           1   

   AirCraftCondition:landState  AirCraftCondition:UP_acc_t  \
0                            1                         0.0   
1                            1                         0.0   
2                            1                         0.0   
3                            1                         0.0   
4                            1                         0.0   

   AirCraftCondition:UP_TF_t  IMUEX(0):err_GPS_CONSIST_ERROR  \
0                          0                               0   
1                          0                               0   
2                          0                               0   
3                          0                               0   
4                          0                               0   

   IMUEX(0):err_NONE  IMUEX(1):err_NONE  AirCraftCondition:nearGround_True  
0                  1                  1                                  1  
1                  1                  1                                  1  
2                  1                  1                                  1  
3                  1                  1                                  1  
4                  1                  1                                  1  

[5 rows x 141 columns]

In [77]:

tick_column = judge_ohe['Tick#']


# Create an imputer instance
imputer = SimpleImputer(strategy='median')  # You can choose a different strategy like 'median' or 'most_frequent'
missing_counts = pd.DataFrame({'variable_name': missing_values.index, 'num_of_missing_values': missing_values.values})
judge_data_ohe_imputed = X_train_ohe.fillna(X_train_ohe.mean())
print(judge_ohe.columns)
judge_ohe['AirCraftCondition:nearGround_False'] = 0
print(judge_ohe.head())
"""
# Fit and transform the imputer on your feature matrix
judge_imputed = imputer.fit_transform(judge_ohe)

# Select the 'Tick#' column as a numeric Series
Tick_Judge = judge_df['Tick#']

# Calculate correlations with the 'Tick#' column
# correlation = judge_imputed.corrwith(tick_column).abs().sort_values(ascending=False).head(75)

# judge_t75 = pd.DataFrame({'variable': correlation.index, 'corr_score': correlation.values})
# top75_variables = judge_t75['variable'].tolist()
"""

Index(['Tick#', 'offsetTime', 'IMU_ATTI(0):numSats',
       'IMU_ATTI(0):barometer:Raw', 'IMU_ATTI(0):barometer:Smooth',
       'IMU_ATTI(0):accel:X', 'IMU_ATTI(0):accel:Y', 'IMU_ATTI(0):accel:Z',
       'IMU_ATTI(0):accel:Composite', 'IMU_ATTI(0):gyro:X',
       ...
       'MotorCtrl:PWM:RBack', 'AirCraftCondition:fsmState',
       'AirCraftCondition:landState', 'AirCraftCondition:UP_acc_t',
       'AirCraftCondition:UP_TF_t', 'IMUEX(0):err_GPS_CONSIST_ERROR',
       'IMUEX(0):err_NONE', 'IMUEX(1):err_NONE',
       'AirCraftCondition:nearGround_True',
       'AirCraftCondition:nearGround_False'],
      dtype='object', length=142)
       Tick#  offsetTime  IMU_ATTI(0):numSats  IMU_ATTI(0):barometer:Raw  \
0  143222258       0.000                   11                   1230.502   
1  143393138       0.044                   11                   1230.502   
2  143566452       0.089                   11                   1230.404   
3  143758752       0.139                   11            

"\n# Fit and transform the imputer on your feature matrix\njudge_imputed = imputer.fit_transform(judge_ohe)\n\n# Select the 'Tick#' column as a numeric Series\nTick_Judge = judge_df['Tick#']\n\n# Calculate correlations with the 'Tick#' column\n# correlation = judge_imputed.corrwith(tick_column).abs().sort_values(ascending=False).head(75)\n\n# judge_t75 = pd.DataFrame({'variable': correlation.index, 'corr_score': correlation.values})\n# top75_variables = judge_t75['variable'].tolist()\n"

In [78]:
judge_data_t75 = judge_ohe[top75_variables]
print(len(judge_data_t75.columns))
judge_data_t75_scaled = scaler.fit_transform(judge_data_t75)


75


In [82]:
from sklearn.impute import SimpleImputer

# Initialize the imputer
imputer = SimpleImputer(strategy='mean')

# Fit and transform the imputer on your feature matrix
judge_data_t75_imputed = imputer.fit_transform(judge_data_t75_scaled)


In [83]:
judge_data_t75_scaled.dropna(inplace=True)


AttributeError: 'numpy.ndarray' object has no attribute 'dropna'

In [84]:
predicted_probabilities = rf_classifier.predict(judge_data_t75_scaled)
class_labels = ['Resting', 'Taking-Off', 'Hovering', 'Climbing', 'Landing']
predicted_operating_phase_labels = [class_labels[np.argmax(prediction)] for prediction in predicted_probabilities]
new_dataset = judge_df[["Tick#"]].copy()
new_dataset["Operating_Phase"] = predicted_operating_phase_labels
new_dataset.to_csv("new_dataset_with_tick_and_operating_phase.csv", index=False)

ValueError: Input X contains NaN.
RandomForestClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values